\c products_dev;

INSERT INTO products (name, image, category, manufacturer, cost, rating, inStock) VALUES
    ('iPhone 12', 'https://store.storeimages.cdn-apple.com/4982/as-images.apple.com/is/refurb-iphone-12-black-2020?wid=1144&hei=1144&fmt=jpeg&qlt=90&.v=1635202741000', 'Electronics', 'Apple', 999.99, 4.5, true),
    ('Samsung TV', 'https://image-us.samsung.com/SamsungUS/home/television-home-theater/tvs/crystal-uhd-tvs/03242023/CU8000.jpg?$product-details-jpg$', 'Electronics', 'Samsung', 699.99, 4.2, true),
    ('Nike Air Max', 'https://static.nike.com/a/images/t_PDP_864_v1/f_auto,b_rgb:f5f5f5/zwxes8uud05rkuei1mpt/air-max-90-mens-shoes-6n3vKB.png', 'Footwear', 'Nike', 129.99, 4.7, true),
    ('PlayStation 5', 'https://media.gamestop.com/i/gamestop/11108141?$pdp2x$$&fmt=webp', 'Electronics', 'Sony', 499.99, 4.8, true),
    ('Canon EOS 80D', 'https://m.media-amazon.com/images/I/71HRe0UwSaL._AC_SX679_.jpg', 'Electronics', 'Canon', 1199.99, 4.6, true),
    ('Adidas Ultraboost', 'https://assets.adidas.com/images/h_840,f_auto,q_auto,fl_lossy,c_fill,g_auto/62ba42e3b71e456298bcaf00018ad40f_9366/Ultraboost_1.0_Shoes_Black_HQ4199_04_standard.jpg', 'Footwear', 'Adidas', 169.99, 4.3, true),
    ('MacBook Pro', 'https://store.storeimages.cdn-apple.com/4982/as-images.apple.com/is/mbp14-spacegray-select-202301?wid=904&hei=840&fmt=jpeg&qlt=90&.v=1671304673229', 'Electronics', 'Apple', 1999.99, 4.7, true),
    ('LG 4K UHD Monitor', 'https://m.media-amazon.com/images/I/71819szMM8L._AC_SX679_.jpg', 'Electronics', 'LG', 499.99, 4.4, true),
    ('Dell XPS 13', 'https://i.dell.com/is/image/DellContent/content/dam/ss2/product-images/dell-client-products/notebooks/xps-notebooks/xps-13-9315/media-gallery/notebook-xps-9315-nt-blue-gallery-3.psd?fmt=png-alpha&pscan=auto&scl=1&hei=402&wid=575&qlt=100,1&resMode=sharp2&size=575,402&chrss=full', 'Electronics', 'Dell', 1299.99, 4.5, true),
    ('Nike Zoom Pegasus', 'https://dks.scene7.com/is/image/GolfGalaxy/22NIKMPGSS39RGMNTRNN_Black_White_Smoke_Grey?qlt=70&wid=992&fmt=webp', 'Footwear', 'Nike', 99.99, 4.2, true),
    ('Sony WH-1000XM4', 'https://pisces.bbystatic.com/image2/BestBuy_US/images/products/6408/6408356cv11d.jpg;maxHeight=2000;maxWidth=2000', 'Electronics', 'Sony', 349.99, 4.8, true),
    ('Samsung Galaxy S21', 'https://pisces.bbystatic.com/image2/BestBuy_US/images/products/6472/6472892cv18d.jpg;maxHeight=640;maxWidth=550', 'Electronics', 'Samsung', 799.99, 4.6, true),
    ('Puma RS-X', 'https://images.footlocker.com/is/image/EBFL2/38989601_a1?wid=500&hei=500&fmt=png-alpha', 'Footwear', 'Puma', 89.99, 4.1, true),
    ('HP Pavilion Laptop', 'https://ssl-product-images.www8-hp.com/digmedialib/prodimg/lowres/c08114736.png?imdensity=1&imwidth=175', 'Electronics', 'HP', 899.99, 4.3, true),
    ('Bose QuietComfort 35 II', 'https://www.backmarket.com/cdn-cgi/image/format%3Dauto%2Cquality%3D75%2Cwidth%3D828/https://d28i4xct2kl5lp.cloudfront.net/product_images/None_9c5fd342-4719-424c-8817-4e455f688082.jpg', 'Electronics', 'Bose', 299.99, 4.7, true),
    ('Nike Air Force 1', 'https://static.nike.com/a/images/t_PDP_864_v1/f_auto,b_rgb:f5f5f5/b7d9211c-26e7-431a-ac24-b0540fb3c00f/air-force-1-07-mens-shoes-jBrhbr.png', 'Footwear', 'Nike', 79.99, 4.4, true),
    ('Samsung Galaxy Tab S7', 'https://image-us.samsung.com/SamsungUS/home/mobile/tablets/galaxy-tab-s7-fe/GalaxyTabS7plusLite_Combo_001_MysticSilver_1600x1200.png?$product-details-jpg$', 'Electronics', 'Samsung', 649.99, 4.5, true),
    ('Vans Old Skool', 'https://images.vans.com/is/image/Vans/VN000D3H_Y28_HERO?wid=800&hei=997&fmt=jpeg&qlt=50&resMode=sharp2&op_usm=0.9,1.5,8,0', 'Footwear', 'Vans', 59.99, 4.3, true),
    ('Google Pixel 5', 'https://www.backmarket.com/cdn-cgi/image/format%3Dauto%2Cquality%3D75%2Cwidth%3D828/https://d28i4xct2kl5lp.cloudfront.net/product_images/None_ed472688-53ee-42de-9a7c-2adcddea7324.jpg', 'Electronics', 'Google', 699.99, 4.5, true),
    ('Converse Chuck Taylor All Star', 'https://cdn-fsly.yottaa.net/57f4626c312e584b1a000020/www.tillys.com/v~4b.214.0.0/on/demandware.static/-/Sites-master-catalog/default/dwc0b79dd8/tillys/images/catalog/1000x1000/159469100.jpg?yocs=y_l_x_', 'Footwear', 'Converse', 49.99, 4.2, true),
    ('To Kill a Mockingbird', 'https://m.media-amazon.com/images/I/51saylYWD-L._SY291_BO1,204,203,200_QL40_FMwebp_.jpg', 'Books', 'Harper Lee', 25.99, 4.5, true),
    ('The Great Gatsby', 'https://m.media-amazon.com/images/I/41NssxNlPlS._SY291_BO1,204,203,200_QL40_FMwebp_.jpg', 'Books', 'F. Scott Fitzgerald', 19.99, 4.2, true),
    ('Pride and Prejudice', 'https://m.media-amazon.com/images/I/416K+gR7RLL._SX303_BO1,204,203,200_.jpg', 'Books', 'Jane Austen', 18.99, 4.7, true),
    ('KitchenAid Blender', 'https://images.thdstatic.com/productImages/23f4ea81-d880-4e01-bf60-2165bdcd2c4f/svn/black-matte-kitchenaid-countertop-blenders-ksb1325bm-64_100.jpg', 'Home Appliances', 'KitchenAid', 89.99, 4.3, true),
    ('Cuisinart Coffee Maker', 'https://pisces.bbystatic.com/image2/BestBuy_US/images/products/6415/6415941_sd.jpg;maxHeight=640;maxWidth=550', 'Home Appliances', 'Cuisinart', 59.99, 4.6, true),
    ('Dyson Air Purifier', 'https://m.media-amazon.com/images/I/61sG2G23BYL._AC_SX679_.jpg', 'Home Appliances', 'Dyson', 299.99, 4.8, true),
    ('Wilson Tennis Racket', 'https://m.media-amazon.com/images/I/71X5-rqXIjL._AC_SX679_.jpg', 'Sports Equipment', 'Wilson', 129.99, 4.4, true),
    ('Adidas Soccer Ball', 'https://m.media-amazon.com/images/I/71OKVGeEqvL._AC_SX679_.jpg', 'Sports Equipment', 'Adidas', 29.99, 4.2, true),
    ('1984', 'https://m.media-amazon.com/images/I/41aM4xOZxaL._SX277_BO1,204,203,200_.jpg', 'Books', 'George Orwell', 22.99, 4.8, true),
    ('The Catcher in the Rye', 'https://m.media-amazon.com/images/I/51haSD7FikS._SY291_BO1,204,203,200_QL40_FMwebp_.jpg', 'Books', 'J.D. Salinger', 17.99, 4.1, true),
    ('Instant Pot Pressure Cooker', 'https://m.media-amazon.com/images/I/71LmN7FsaZL._AC_SX679_.jpg', 'Home Appliances', 'Instant Pot', 99.99, 4.5, true);


INSERT INTO reviews (title, reviewer, content, products_id) VALUES
    ('Great phone!', 'John Doe', 'I love the iPhone 12. It has an amazing camera and great performance.', 1),
    ('Highly recommended', 'Jane Smith', 'The iPhone 12 is worth every penny. The display quality is excellent.', 1),
    ('Decent smartphone', 'David Johnson', 'The iPhone 12 has good battery life and a sleek design.', 1),
    ('Impressive picture quality', 'Sara Thompson', 'The Samsung TV delivers stunning visuals. The colors are vibrant and the contrast is fantastic.', 2),
    ('Great value for money', 'Michael Brown', 'I am very satisfied with my purchase of the Samsung TV. The picture and sound quality are top-notch.', 2),
    ('Not as expected', 'Emily Davis', 'I had high expectations from the Samsung TV, but I found the user interface to be clunky.', 2),
    ('Comfortable and stylish', 'Jessica Wilson', 'The Nike Air Max shoes are extremely comfortable to wear and look great with any outfit.', 3),
    ('Excellent running shoes', 'Robert Taylor', 'I highly recommend the Nike Air Max for running. They provide excellent cushioning and support.', 3),
    ('Disappointed with durability', 'Jennifer Martinez', 'Although the Nike Air Max shoes are comfortable, I noticed signs of wear and tear after a few months of use.', 3),
    ('Unparalleled gaming experience', 'Daniel Clark', 'The PlayStation 5 is a true gaming powerhouse. The graphics and performance are unmatched.', 4),
    ('Hours of entertainment', 'Laura Anderson', 'I''m loving the PlayStation 5. It offers a wide variety of games and keeps me entertained for hours.', 4),
    ('Difficult to find in stock', 'Mark Roberts', 'The only downside of the PlayStation 5 is its availability. It''s been challenging to find one in stock.', 4),
    ('Great for photography enthusiasts', 'Jennifer Hill', 'The Canon EOS 80D is a fantastic camera for both beginners and advanced photographers.', 5),
    ('Impressive image quality', 'Andrew Mitchell', 'The Canon EOS 80D produces sharp and vibrant images. It''s a reliable camera for all occasions.', 5),
    ('Not suitable for low-light photography', 'Sarah Adams', 'I found the Canon EOS 80D to struggle in low-light conditions. The noise levels were higher than expected.', 5),
    ('Comfortable and stylish', 'Peter Wilson', 'The Adidas Ultraboost shoes are not only comfortable for running but also look stylish for everyday wear.', 6),
    ('Great for long-distance running', 'Michelle Turner', 'I have been using the Adidas Ultraboost for marathon training, and they provide excellent comfort and support.', 6),
    ('Durability concerns', 'Christopher Lee', 'While the Adidas Ultraboost shoes offer great comfort, I noticed some durability issues after several months of use.', 6),
    ('Excellent for creative work', 'Sophia Roberts', 'The MacBook Pro is a go-to choice for designers and video editors. It offers seamless performance and a stunning display.', 7),
    ('Highly reliable and fast', 'Michael Thompson', 'I have been using the MacBook Pro for years, and it has never let me down. The speed and reliability are unmatched.', 7),
    ('Great for productivity', 'Emily Wilson', 'The MacBook Pro has been a game-changer for my work. It helps me stay organized and boosts my efficiency.', 7),
    ('Crisp and vibrant visuals', 'Daniel Brown', 'The LG 4K UHD Monitor provides an immersive viewing experience. The colors are rich, and the details are sharp.', 8),
    ('Multiple connectivity options', 'Sophia Davis', 'I love the LG 4K UHD Monitor for its versatility. It offers a wide range of connectivity options to connect multiple devices.', 8),
    ('Adjustable stand', 'Matthew Anderson', 'The adjustable stand of the LG 4K UHD Monitor is a great feature. It allows me to find the perfect viewing angle for my comfort.', 8),
    ('Sleek and portable', 'Olivia Clark', 'The Dell XPS 13 is a lightweight and slim laptop, perfect for travelers. It doesn''t compromise on performance either.', 9),
    ('Impressive display', 'James Mitchell', 'The Dell XPS 13 has a stunning display with vibrant colors and excellent clarity. Watching movies and editing photos is a delight.', 9),
    ('Fast and responsive', 'Emma Turner', 'The Dell XPS 13 is incredibly fast and responsive. It handles multitasking with ease, making it ideal for work and entertainment.', 9),
    ('Great running shoes', 'Jacob Wilson', 'The Nike Zoom Pegasus shoes offer excellent cushioning and support. They have improved my running experience significantly.', 10),
    ('Lightweight and breathable', 'Sophie Adams', 'I love the lightweight and breathable design of the Nike Zoom Pegasus. It keeps my feet cool and comfortable during long runs.', 10),
    ('Durable and long-lasting', 'Ryan Thompson', 'The Nike Zoom Pegasus shoes are built to last. Even after extensive use, they show minimal signs of wear and tear.', 10),
    ('Top-notch noise cancellation', 'Grace Martinez', 'The Sony WH-1000XM4 headphones have exceptional noise cancellation. They block out background noise effectively.', 11),
    ('Crystal-clear sound', 'David Turner', 'The sound quality of the Sony WH-1000XM4 is outstanding. The audio is crisp and well-balanced across various genres.', 11),
    ('Comfortable for long listening sessions', 'Emily Roberts', 'I can wear the Sony WH-1000XM4 headphones for hours without discomfort. The cushioning and adjustable headband provide a perfect fit.', 11),
    ('Impressive camera performance', 'Daniel Wilson', 'The Samsung Galaxy S21 takes stunning photos with great detail and vibrant colors. It''s a photographer''s dream smartphone.', 12),
    ('Smooth and responsive', 'Sophia Turner', 'The Samsung Galaxy S21 offers a smooth and responsive user experience. Apps load quickly, and multitasking is a breeze.', 12);



